"""Generate ``paper/numbers.tex`` from ``paper/results.json``.

Numeric macros only. The narrative macros live in ``paper/narrative.tex`` and are
written by hand.

Every number that appears in the manuscript comes from here, so no figure in the
prose is transcribed by hand. If a number in the paper disagrees with the
experiments, that is a bug in this file rather than a typo somewhere in the text.

Usage::

    python scripts/fill_numbers.py --results paper/results.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    args = _parse_args()
    payload = json.loads(Path(args.results).read_text(encoding="utf-8"))
    output = Path(args.out)

    controllers = {c["key"]: c for c in payload["controllers"]}
    conditions = payload["conditions"]
    feasible = sum(1 for c in conditions if c["feasible"])

    lines = [
        "% Generated by scripts/fill_numbers.py -- do not edit numeric macros by hand.",
        _macro("FlutterSpeed", f"{payload['flutter_speed']:.2f}"),
        _macro("FeasibleCells", str(feasible)),
        _macro("TotalCells", str(len(conditions))),
    ]

    for key, controller in controllers.items():
        name = _camel(key)
        lines.append(_macro(f"{name}Stabilised", str(controller["stabilised"])))
        healthy = controller["healthy_suppression"]
        healthy_text = "n/a" if healthy != healthy else f"{healthy:.2f}"
        lines.append(_macro(f"{name}Healthy", healthy_text))

    learned = [c for c in payload["controllers"] if c["kind"] == "learned"]
    if learned:
        best_robust = max(learned, key=lambda c: c["stabilised"])
        best_nominal = min(
            (c for c in learned if c["healthy_suppression"] == c["healthy_suppression"]),
            key=lambda c: c["healthy_suppression"],
            default=best_robust,
        )
        lines += [
            _macro("BestRobustVariant", _escape(best_robust["key"])),
            _macro("BestRobustStabilised", str(best_robust["stabilised"])),
            _macro("BestNominalVariant", _escape(best_nominal["key"])),
            _macro("BestNominalHealthy", f"{best_nominal['healthy_suppression']:.2f}"),
        ]

    # Narrative macros deliberately live in paper/narrative.tex and are written
    # by hand. Prose that argues a direction must not come from a template when
    # the direction is exactly what the experiments decide -- this study reversed
    # it three times before the measurements were trustworthy.

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {output} with {len(lines) - 1} macros")
    print(f"  feasible cells: {feasible}/{len(conditions)}")
    for controller in payload["controllers"]:
        healthy = controller["healthy_suppression"]
        text = "n/a" if healthy != healthy else f"{healthy:+.2f}"
        print(
            f"  {controller['key']:16s} {controller['kind']:9s} "
            f"stabilised {controller['stabilised']}/{controller['feasible_cells']}"
            f"   healthy {text}"
        )


def _macro(name: str, body: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{body}}}"


def _camel(key: str) -> str:
    return "".join(part.capitalize() for part in key.split("_"))


def _escape(text: str) -> str:
    return text.replace("_", r"\_")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="paper/results.json")
    parser.add_argument("--out", default="paper/numbers.tex")
    return parser.parse_args()


if __name__ == "__main__":
    main()
