"""Compare the VDN-style learned credit baseline against the closed-form credit.

Answers the Devil's Advocate's Critical #1 finding directly: the manuscript
argued its closed-form credit is better than "standard remedies" (VDN/QMIX/
COMA) without ever running one. This loads the freshly-trained ``vdn_shared``
and 6-seed ``ippo_shared`` runs (see ``scripts/train_agents.py``'s
``vdn_shared``/``ippo_shared`` presets) and compares them against the existing
credit-ablation's published summary statistics (mean, std, n=6 for
``ippo_physics``/``ippo_blended``, already in ``paper/ablation_credit.tex``)
using ``scipy.stats.ttest_ind_from_stats``, which needs only summary statistics
-- the original per-seed run archive for those groups is not present in this
checkout, but comparing from published summary statistics against freshly
computed raw data is statistically valid for a two-sample Welch's t-test.

Usage::

    python scripts/vdn_comparison.py --vdn-runs runs/vdn_shared \\
        --shared-runs runs/ippo_shared_6seed
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from scipy import stats

# From paper/ablation_credit.tex, generated by scripts/ablation_stats.py against
# the original (not-present-in-this-checkout) runs/credit_fine archive.
PUBLISHED = {
    "ippo_physics": (-0.566, 0.123, 6),
    "ippo_blended": (-1.085, 0.243, 6),
    "shaped_shared": (-0.690, 0.145, 6),
}


def _load_healthy_decay(runs: Path) -> np.ndarray:
    values = []
    for path in sorted(runs.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        healthy = [
            r["suppression_rate"]
            for r in payload["results"]
            if r["condition"]["jam_surface"] < 0 and r["divergence_rate"] == 0.0
        ]
        if healthy:
            values.append(float(np.mean(healthy)))
    return np.asarray(values)


def _hedges_g(effect: float, n1: int, n2: int) -> float:
    correction = 1.0 - 3.0 / (4.0 * (n1 + n2) - 9.0) if n1 + n2 > 2 else float("nan")
    return effect * correction


def _compare_to_published(name: str, values: np.ndarray) -> None:
    mean, std, n = np.mean(values), np.std(values, ddof=1), values.size
    print(f"{name}: {mean:+.3f} +- {std:.3f}  (n={n})")
    for other, (o_mean, o_std, o_n) in PUBLISHED.items():
        statistic, pvalue = stats.ttest_ind_from_stats(
            mean, std, n, o_mean, o_std, o_n, equal_var=False
        )
        pooled = np.sqrt((std**2 + o_std**2) / 2.0)
        effect = (mean - o_mean) / pooled if pooled > 0 else float("nan")
        g = _hedges_g(effect, n, o_n)
        marker = "  SIGNIFICANT" if pvalue < 0.05 else ""
        print(
            f"  vs {other:14s} (published {o_mean:+.3f}+-{o_std:.3f}, n={o_n}):  "
            f"diff {mean - o_mean:+.3f}  d {effect:+.2f}  g {g:+.2f}  "
            f"p = {pvalue:.4f}{marker}"
        )
        del statistic


def main() -> None:
    args = _parse_args()
    vdn = _load_healthy_decay(Path(args.vdn_runs))
    shared = _load_healthy_decay(Path(args.shared_runs))

    print("Learned value-decomposition credit (VDN-style) vs. closed-form "
          "physics credit and vs. the naive undecomposed shared-reward "
          "baseline, all now at n=6:\n")
    _compare_to_published("vdn_shared", vdn)
    print()
    _compare_to_published("ippo_shared (6-seed)", shared)
    print()

    statistic, pvalue = stats.ttest_ind(vdn, shared, equal_var=False)
    pooled = np.sqrt((vdn.var(ddof=1) + shared.var(ddof=1)) / 2.0)
    effect = (vdn.mean() - shared.mean()) / pooled if pooled > 0 else float("nan")
    g = _hedges_g(effect, vdn.size, shared.size)
    print(
        f"vdn_shared vs ippo_shared (6-seed, both raw data): "
        f"diff {vdn.mean() - shared.mean():+.3f}  d {effect:+.2f}  g {g:+.2f}  "
        f"p = {pvalue:.4f}"
    )
    del statistic


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vdn-runs", default="runs/vdn_shared")
    parser.add_argument("--shared-runs", default="runs/ippo_shared_6seed")
    return parser.parse_args()


if __name__ == "__main__":
    main()
